[versions]
kotlin = "2.0.21"
junit5 = "5.11.3"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = "org.jetbrains.compose:1.7.0"

[libraries]
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
